apiVersion: v2
name: common
description: A library chart for common templates and helper functions
type: library
version: 2.1.2
appVersion: "2.1.2"
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/common
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
annotations:
  license: Apache-2.0
  artifacthub.io/changes: |2
        - kind: changed
          description: "Fix YAML parse error caused by whitespace control in selectorLabels (#919)"
          links:
            - name: "Commit 4ab389c"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/4ab389c"
