apiVersion: v2
name: common
description: A library chart for common templates and helper functions
type: library
version: 2.1.1
appVersion: "2.1.1"
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/common
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
annotations:
  license: Apache-2.0
  artifacthub.io/changes: |2
        - kind: changed
          description: "rename templates from common.* to cloudpirates.* to prevent collisions (#377)"
          links:
            - name: "Commit 07c6560"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/07c6560"
