apiVersion: v2
name: nginx
description: Nginx is a high-performance HTTP server and reverse proxy.
type: application
version: 0.6.0
appVersion: "1.29.5"
keywords:
  - nginx
  - web server
  - http
  - reverse proxy
  - load balancer
  - proxy
home: https://www.nginx.com
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/nginx
  - https://github.com/nginx/nginx
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.2.0"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/9fcd98c061/nginx-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: networking
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: Nginx
      url: https://www.nginx.com
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/nginx
    - name: Application
      url: https://github.com/nginx/nginx
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: changed
          description: "[nginx]: Allow loading site from configmap (#935)"
          links:
            - name: "Commit ff72433"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/ff72433"
        - kind: changed
          description: "[all]: Update documentation to include proper cosign public key"
          links:
            - name: "Commit e42365d"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/e42365d"
