{{- if and (or .Values.replicaSet.enabled .Values.shardedCluster.enabled) (or .Values.auth.enabled .Values.replicaSet.key .Values.shardedCluster.keyFile) }}
{{- if not (or .Values.replicaSet.keySecretName .Values.shardedCluster.keySecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.keyfileSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- with (include "mongodb.annotations" .) }}
  annotations:
{{- . | indent 4 }}
  {{- end }}
type: Opaque
data:
  keyfile: {{ (coalesce .Values.shardedCluster.keyFile .Values.replicaSet.key) | b64enc | quote }}
{{- end }}
{{- end }}
