{{- if .Values.shardedCluster.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mongodb.fullname" . }}-init-sharded
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mongodb.fullname" . }}-init-sharded
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mongodb.fullname" . }}-init-sharded
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
