{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.metrics.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annotations := merge .Values.metrics.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: {{ .Values.metrics.service.port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
{{- end }}
