{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
  {{- with (include "zookeeper.annotations" .) }}
  annotations: 
{{- . | indent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "zookeeper.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    {{- if .Values.metrics.enabled }}
    # Allow metrics scraping
    - ports:
        - port: {{ .Values.metrics.service.port }}
          protocol: TCP
    {{- end }}
    # Allow inbound connections to ZooKeeper
    - ports:
        - port: {{ .Values.service.ports.client | default 2181 }}
    # Allow internal communications between nodes
    - ports:
        - port: {{ .Values.service.ports.quorum | default 2888 }}
        - port: {{ .Values.service.ports.leaderElection | default 3888 }}
      from:
        - podSelector:
            matchLabels:
            {{- include "zookeeper.labels" . | nindent 12 }}
{{- end }}
