{{- if not .Values.auth.existingSecret }}
{{- $secretName := include "rabbitmq.fullname" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
  {{- with (include "rabbitmq.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.password }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data (index $existingSecret.data "password") }}
  password: {{ index $existingSecret.data "password" | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.erlangCookie }}
  erlang-cookie: {{ .Values.auth.erlangCookie | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data (index $existingSecret.data "erlang-cookie") }}
  erlang-cookie: {{ index $existingSecret.data "erlang-cookie" | quote }}
  {{- else }}
  erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}